# -*- coding: utf-8 -*-
"""webScrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXTCQXqqUZWmn7C6Bevm3mtseDv5wHs7
"""

from urllib.request import urlopen
url = "https://en.wikipedia.org/wiki/Android_(operating_system)"
data = urlopen(url)
print(type(data))
and_html = data.read()
print(and_html)

